Refer to original source metadata in source XML and JSON
SAR-ARD/S1_NRB pull request #136
Opened 2023-09-13 08:53 UTC by maawoo

closes #120 

Here is a preview of how the files are listed in the source XML and JSON files:
<img width="1590" alt="image" src="https://github.com/SAR-ARD/S1_NRB/assets/56583917/5e31ab6e-0532-43ee-8437-29cdaeeb3997">

2023-09-14 12:35 UTC, johntruckenbrodt requested changes
Looks good @maawoo. I only found a very minor thing.
Could you upload some example files here so I can have a look?

2023-09-14 12:35 UTC, johntruckenbrodt commented on S1_NRB/nrb.py
> +        schema_out = os.path.join(os.path.join(ard_dir, 'support'), schema)
double `os.path.join`
```python
schema_out = os.path.join(ard_dir, 'support', schema)
```

2023-09-15 08:28 UTC, maawoo commented
[Here](https://upload.uni-jena.de/data/65041564ea2064.00247820/S1B_IW_ORB__1SDV_20211114T190503_029588_0387F4_28RDS_A80B.zip) you go (accessible until 1 week from now)

2023-09-15 08:28 UTC, maawoo commented on S1_NRB/nrb.py
> +        schema_out = os.path.join(os.path.join(ard_dir, 'support'), schema)
Whoops, fixed https://github.com/SAR-ARD/S1_NRB/pull/136/commits/43575a4e12562a2372e3c85e26b53d8d9ea01766

2023-09-18 08:11 UTC, johntruckenbrodt commented
@maawoo what happens if there are two source scenes? Won't there be double keys in the metadata?

2023-09-18 09:06 UTC, maawoo commented
> @maawoo what happens if there are two source scenes? Won't there be double keys in the metadata?

The XML and JSON files are generated for each source scene individually. So duplicate keys shouldn't be an issue.
Feel free to check this example: https://upload.uni-jena.de/data/6508122e960422.78001587/S1B_IW_ORB__1SDV_20211114T190517_029588_0387F4_28RDT_7A8C.zip

2023-09-18 11:26 UTC, johntruckenbrodt commented
Of course. Monday morning I guess 😅.

2023-09-18 11:26 UTC, johntruckenbrodt approved these changes

2023-09-18 11:27 UTC, merged